server:
  port: ${COMPANY_SERVICE_PORT:8082}

spring:
  application:
    name: company-service
  profiles:
    active: ${APP_PROFILE:production}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/company_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml

resilience4j:
  retry:
    instances:
      userServiceClient:
        maxAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      userServiceClient:
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 10

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true